### ISSUE TITLE
在chrome浏览器下，选择图片反应比较慢

### ISSUE THREAD

**Issue by ccfish86** [Gump8/ldf-img#2]
可能是使用了image/*，导致浏览器会向google请求对应的数据，下面是通过fiddler抓到的，每点一次图片上传，都会请求一次google。以天朝网络，这个不太合理。可不可以改为`accept="image/gif,image/png,image/jpeg,image/jpg,image/bmp"`

ldf-img里的dom`<input id="inputfile" type="file" accept="image/*">`

验证：
![image](https://user-images.githubusercontent.com/15622514/29067121-0314b5f0-7c64-11e7-8992-9117757dcd9a.png)

参考：[https://segmentfault.com/a/1190000010397414](url)

**Comment by Gump8** [comment]
Thank you!  
你可能用了64位的,  建议使用chrome 32位版本的.  chrome 64位的非常占内存且容易崩溃. 
如果改成   accept="image/*"  ,  在iOS中会出现不能拍照上传的情况.
我正在考虑如何解决这个问题: 或许可以加个判断, 只在chrome 64位版本中使用如你建议的, 你觉得如何?

**Comment by ccfish86** [comment]
当然可以只针对chrome修改，因为国内暂时也只有google的无法正常访问

**Comment by Gump8** [comment]
已更改, 请你测试一下.   Thank you!

**Comment by ccfish86** [comment]
这么样，在PC端的Chrome下应该是正常了，但开发者模式下agent会被模拟成其他类型的浏览器，这时还会存在问题。但这种情况下，应该可以不用处理。
`User-Agent:Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1 EXT/1b00d6agqpx0c73611e6a485e5b19b17ef2d/7.1
Name`
