### ISSUE TITLE
57K的图片经处理后变成了187K

### ISSUE THREAD

**Issue by ccfish86** [Gump8/ldf-img#4]
可能是处理压缩率的问题，jpeg文件如果>0.92压缩率的话，压缩后体积会变大
![image](https://user-images.githubusercontent.com/15622514/29269936-c0c5c1fe-8126-11e7-828d-3cdf03bb4550.png)

可能出现在这地方的压缩率这儿
`let newImgData = canvas.toDataURL(fileType, 1)`

**Comment by ccfish86** [comment]
此外，还有个地方，也不应该判断1，最好是0.92
```
//大于 1 时, 不再进行质量压缩, 保存最终返回的数据
if (compressSizeRate >= 1) {
```

**Comment by Gump8** [comment]
最近比较忙........
只知道canvas默认会有0.92的压缩.  这个还真没想到

**Comment by Gump8** [comment]
最近比较忙........
只知道canvas默认会有0.92的压缩.  这个还真没想到

**Comment by Gump8** [comment]
最近比较忙........
只知道canvas默认会有0.92的压缩.  这个还真没想到

**Comment by Gump8** [comment]
已更改
